In [2]:
import tensorflow as tf
import pandas as pd

In [3]:
iris_url = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris_csv = pd.read_csv(iris_url)
iris_csv.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [4]:
iris_csv = iris_csv.rename(columns={'꽃잎길이':'sepal length','꽃잎폭':'sepal width','꽃받침길이':'petal length','꽃받침폭':'petal width','품종':'label'})
iris_csv.head()


sepal length  sepal width  petal length  petal width   label
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
iris_df = pd.get_dummies(iris_csv)
iris_df.head()

sepal length  sepal width  ...  label_versicolor  label_virginica
0           5.1          3.5  ...                 0                0
1           4.9          3.0  ...                 0                0
2           4.7          3.2  ...                 0                0
3           4.6          3.1  ...                 0                0
4           5.0          3.6  ...                 0                0

[5 rows x 7 columns]

In [6]:
iris_feature = iris_df[['sepal length','sepal width','petal length','petal width']]
iris_label = iris_df[['label_setosa','label_versicolor','label_virginica']]

In [7]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [8]:
model.fit(iris_feature, iris_label, epochs=10000, verbose=0)
model.fit(iris_feature, iris_label, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0536 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0534 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0535 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0532 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0534 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0540 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0535 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0535 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0536 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0535 - accuracy: 0.9800


In [9]:
print(model.predict(iris_feature[:5]))
print(iris_label[:5])

[[1.0000000e+00 2.5548615e-11 2.0220741e-24]
 [1.0000000e+00 2.4429418e-09 2.4759042e-21]
 [1.0000000e+00 2.7616856e-10 1.2711740e-22]
 [1.0000000e+00 7.6814919e-09 1.8119500e-20]
 [1.0000000e+00 1.5071541e-11 1.0246630e-24]]
   label_setosa  label_versicolor  label_virginica
0             1                 0                0
1             1                 0                0
2             1                 0                0
3             1                 0                0
4             1                 0                0


In [10]:
print(model.get_weights())

[array([[  3.963723 ,   1.2187496,  -1.338318 ],
       [  9.6760435,   1.6532854,  -2.4236143],
       [-13.4647045,  -2.2207932,   2.6325943],
       [-16.301912 ,  -3.3206391,   5.8691225]], dtype=float32), array([ 6.2793717,  5.6302233, -5.8597584], dtype=float32)]


In [11]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model_m = tf.keras.models.Model(X, Y)
model_m.compile(loss='categorical_crossentropy',metrics='accuracy')

In [12]:
model_m.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [13]:
model_m.fit(iris_feature, iris_label, epochs=10000, verbose=0)
model_m.fit(iris_feature, iris_label, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 4.0060e-04 - accuracy: 1.0000
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 3.8452e-04 - accuracy: 1.0000
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 3.5410e-04 - accuracy: 1.0000
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 3.3823e-04 - accuracy: 1.0000
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 4.0468e-04 - accuracy: 1.0000
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 5.9475e-04 - accuracy: 1.0000
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 4.9995e-04 - accuracy: 1.0000
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 3.6527e-04 - accuracy: 1.0000
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0109 - accuracy: 0.9933
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0080 - accuracy: 0.9933


In [14]:
print(model.predict(iris_feature[:5]))
print(iris_label[:5])

[[1.0000000e+00 2.5548615e-11 2.0220741e-24]
 [1.0000000e+00 2.4429418e-09 2.4759042e-21]
 [1.0000000e+00 2.7616856e-10 1.2711740e-22]
 [1.0000000e+00 7.6814919e-09 1.8119500e-20]
 [1.0000000e+00 1.5071541e-11 1.0246630e-24]]
   label_setosa  label_versicolor  label_virginica
0             1                 0                0
1             1                 0                0
2             1                 0                0
3             1                 0                0
4             1                 0                0


In [15]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model_m2 = tf.keras.models.Model(X, Y)
model_m2.compile(loss='categorical_crossentropy',metrics='accuracy')

In [17]:
model_m2.fit(iris_feature, iris_label, epochs=10000, verbose=0)
model_m2.fit(iris_feature, iris_label, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1158 - accuracy: 0.9400
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0687 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0279 - accuracy: 0.9933
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0728 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1769 - accuracy: 0.9267
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1374 - accuracy: 0.9400
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0364 - accuracy: 0.9933
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1723 - accuracy: 0.9133
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0475 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0254 - accuracy: 1.0000


In [18]:
print(model.predict(iris_feature[:5]))
print(iris_label[:5])

[[1.0000000e+00 2.5548615e-11 2.0220741e-24]
 [1.0000000e+00 2.4429418e-09 2.4759042e-21]
 [1.0000000e+00 2.7616856e-10 1.2711740e-22]
 [1.0000000e+00 7.6814919e-09 1.8119500e-20]
 [1.0000000e+00 1.5071541e-11 1.0246630e-24]]
   label_setosa  label_versicolor  label_virginica
0             1                 0                0
1             1                 0                0
2             1                 0                0
3             1                 0                0
4             1                 0                0
